name: Update PEP Data

on:
  schedule:
    - cron: '0 5 1 * *' # Run on the 1st of every month at 05:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pep-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: Run Pipeline
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
        run: |
          uv run python scripts/pep_pipeline.py

      - name: Commit newly generated parquet (if any changes)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/data/
          git commit -m "Update PEP Parquet data" || echo "No changes to commit"
          git push
